GET http://localhost:8000/running

###
GET http://localhost:8000/

###

GET http://localhost:8000/api/owner
Authorization: eyJhbGcjfhfjriOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I
###

GET http://localhost:8000/api/owner/6
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJzaW1vbiIsInJvbGUiOiJvd25lciIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4OTk0Nn0.2HwLCMM3AdNY8tHd3QbPKTsoASAoVyz3-Fm-FcCOMfg
###
GET http://localhost:8000/api/owner/6/full
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJzaW1vbiIsInJvbGUiOiJvd25lciIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4OTk0Nn0.2HwLCMM3AdNY8tHd3QbPKTsoASAoVyz3-Fm-FcCOMfg

###
POST  http://localhost:8000/api/ownerinsert
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I
Content-Type: application/json


###
PUT   http://localhost:8000/api/ownerupdate/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I
Content-Type: application/json



###
DELETE  http://localhost:8000/api/ownerdelete/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I
Content-Type: application/json


###
GET http://localhost:8000/api/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I

###
GET http://localhost:8000/api/order/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJzaW1vbiIsInJvbGUiOiJvd25lciIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4OTk0Nn0.2HwLCMM3AdNY8tHd3QbPKTsoASAoVyz3-Fm-FcCOMfg

###
GET http://localhost:8000/api/order/1/full
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJzaW1vbiIsInJvbGUiOiJvd25lciIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4OTk0Nn0.2HwLCMM3AdNY8tHd3QbPKTsoASAoVyz3-Fm-FcCOMfg

###
POST  http://localhost:8000/api/orderinsert
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4MDMwNH0.3yIa4MQPJmg9sRoaeEWXCb2J4EA75n2JeoqxAOffUfU
Content-Type: application/json

 

###
PUT   http://localhost:8000/api/orderupdate/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODE4NzUzN30.TNnDlZ5EWu_QFlB2yG9yLQmCJQps-PG_mwYoDEGZbS0
Content-Type: application/json

###
POST  http://localhost:8000/api/user/insert
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I

###
PUT http://localhost:8000/api/userupdate/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I

###
GET http://localhost:8000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqYW1lcyIsInJvbGUiOiJhZG1pbiIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI5MDE2N30.UsWajnggtrVdUi4UR4HeL0BYjSiSXatehpwhSj4cD-I

###
GET http://localhost:8000/api/user/1/full
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJzaW1vbiIsInJvbGUiOiJvd25lciIsIm93bmVyaWQiOjEsImV4cCI6MTcxODI4OTk0Nn0.2HwLCMM3AdNY8tHd3QbPKTsoASAoVyz3-Fm-FcCOMfg
###
GET http://localhost:8000/api/menuitem
Authorization: 


###
GET http://localhost:8000/api/menuitem/1
Authorization: 
###
POST http://localhost:8000/api/menuinsert
Authorization: 
Content-Type: application/json

 
###
PUT http://localhost:8000/api/menuupdate/1
Authorization: 
Content-Type: application/json

 


###
GET http://localhost:8000/api/menu
Authorization: 

###
GET http://localhost:8000/api/menu/1
Authorization: 

###
POST  http://localhost:8000/api/iteminsert
Authorization: 
Content-Type: application/json



###
PUT   http://localhost:8000/api/updateitem/3
Authorization: 
Content-Type: application/json


###
GET http://localhost:8000/api/driver
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcm5hbWUiOiJqb3ljZSIsInJvbGUiOiJkcml2ZXIiLCJvd25lcmlkIjoxLCJleHAiOjE3MTgyODk4NTV9.W91wPAYxtAJ58ZGEZIAzcFM2r5Qa-uzCQG8GNedmpSo
###
GET http://localhost:8000/api/driver/2
Authorization: 
###
GET http://localhost:8000/api/driver/2/req
Authorization: 

###
POST  http://localhost:8000/api/driverinsert
Authorization: 
Content-Type: application/json

###
PUT   http://localhost:8000/api/updatedriver/5
Authorization: 
Content-Type: application/json



  ###
DELETE   http://localhost:8000/api/updatedriver/5
Authorization: 
Content-Type: application/json
###
GET http://localhost:8000/api/time

###
http://localhost:8000/api/time


###
GET http://localhost:8000/api/city
Authorization: 

###
GET http://localhost:8000/api/city/1
Authorization: 

###
POST http://localhost:8000/api/cityinsert
Authorization: 
Content-Type: application/json



###
PUT  http://localhost:8000/api/cityupdate/4
Authorization: 
Content-Type: application/json




###
DELETE http://localhost:8000/api/cityupdate/4
Authorization: 
Content-Type: application/json

###
GET http://localhost:8000/api/comment
Authorization: 

###
GET http://localhost:8000/api/comment/1
Authorization: 

###
POST http://localhost:8000/api/commentinsert
Authorization: 
Content-Type: application/json



###
PUT  http://localhost:8000/api/comment/2
Authorization: 
Content-Type: application/json

###
DELETE http://localhost:8000/api/comment/2
Authorization: 
Content-Type: application/json

###
GET http://localhost:8000/api/category
Authorization: 

###
GET http://localhost:8000/api/category/1
Authorization: 

###
POST http://localhost:8000/api/categoryinsert
Authorization: 
Content-Type: application/json



###
PUT http://localhost:8000/api/categoryupdate/3
Authorization: 
Content-Type: application/json



###
DELETE  http://localhost:8000/api/categorydelete/3
Authorization: 
Content-Type: application/json

###
GET http://localhost:8000/api/address
Authorization: 


###
GET http://localhost:8000/api/address/1
Authorization: 


###
POST  http://localhost:8000/api/addressinsert
Authorization: 
Content-Type: application/json


###
PUT  http://localhost:8000/api/addressupdate/1
Authorization: 
Content-Type: application/json



###
DELETE  http://localhost:8000/api/addressdelete/1
Authorization:


###
POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "ownerid": 7,
   "ownername": "nancy",
   "password": "owner",
   "role":"chef"
}

###
POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{
   "ownername": "james",
   "password": "owner"
}